# Generated by Django 4.0 on 2021-12-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('dateLimit', models.DateField(blank=True, null=True)),
                ('concluded', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
